Header header
# local frame
string local_frame_id
# position of local_frame_id wrt frame_id
geometry_msgs/Vector3 p
# velocity of local_frame_id wrt frame_id expressed in local_frame_id
geometry_msgs/Vector3 v
# acceleration of local_frame_id wrt frame_id expressed in local_frame_id
geometry_msgs/Vector3 a
# orientation of local_frame_id wrt frame_id
geometry_msgs/Vector3 e
# angular velocity of local_frame_id wrt frame_id expressed in local_frame_id
geometry_msgs/Vector3 w
# angular acceleration of local_frame_id wrt frame_id expressed in local_frame_id
geometry_msgs/Vector3 d
